
dummy:
	echo the target is '"all"'

all: \
  ../source/individual/2018/05/fast_power.txt \
  ../source/individual/2018/05/chomsky_1956.txt

../source/individual/2018/05/fast_power.txt:
	perl fast_power.pl > ../source/individual/2018/05/fast_power.txt

../source/individual/2018/05/chomsky_1956.txt:
	perl chomsky_1956.pl > ../source/individual/2018/05/chomsky_1956.txt
