
dummy:
	echo the target is '"all"'

all: \
  ../source/individual/2018/05/fast_power.txt \
  ../source/individual/2018/05/chomsky_1956.txt \
  ../source/individual/2018/05/knuth_1965.txt \
  ../source/individual/2018/05/pingali.txt \
  ../source/individual/2018/05/csg.txt \
  ../source/individual/2018/05/combinator.txt \
  ../source/individual/2018/05/lrecursion.txt \
  ../source/individual/2018/07/knuth_1965_2.txt \
  ../source/individual/2018/05/combinator2.txt \
  ../source/individual/2018/08/rntz.txt \
  ../source/individual/2018/10/popularity.txt \

../source/individual/2018/05/fast_power.txt: fast_power.pl
	perl fast_power.pl > ../source/individual/2018/05/fast_power.txt

../source/individual/2018/05/chomsky_1956.txt: chomsky_1956.pl
	perl chomsky_1956.pl > ../source/individual/2018/05/chomsky_1956.txt

../source/individual/2018/05/knuth_1965.txt: knuth_1965.pl
	perl knuth_1965.pl > ../source/individual/2018/05/knuth_1965.txt

../source/individual/2018/05/pingali.txt: pingali.pl
	perl pingali.pl > ../source/individual/2018/05/pingali.txt

../source/individual/2018/05/csg.txt: csg.pl
	perl csg.pl > ../source/individual/2018/05/csg.txt

../source/individual/2018/05/combinator.txt: combinator.pl
	perl combinator.pl > ../source/individual/2018/05/combinator.txt

../source/individual/2018/05/lrecursion.txt: lrecursion.pl
	perl lrecursion.pl > ../source/individual/2018/05/lrecursion.txt

../source/individual/2018/07/knuth_1965_2.txt: knuth_1965_2.pl
	perl knuth_1965_2.pl > ../source/individual/2018/07/knuth_1965_2.txt

../source/individual/2018/05/combinator2.txt: combinator2.pl
	perl combinator2.pl > ../source/individual/2018/05/combinator2.txt

../source/individual/2018/08/rntz.txt: rntz.pl
	perl rntz.pl > ../source/individual/2018/08/rntz.txt


../source/individual/2018/10/popularity.txt: popularity.pl
	perl popularity.pl > ../source/individual/2018/10/popularity.txt
